// src/content/hoit/abouttext.ts

// Put your real English and French “About Me” text here.
// The HOIT About section reads these values directly and will not
// be touched by the automatic DOM translator.

export const HOIT_ABOUT_EN = `
Steven Warsh is a Registered Massage Therapist with the AMQ and a Certified Athletic Therapist (AT) with CATA living in Montreal, Quebec who takes an integrative, holistic approach to therapy. He began his training at McGill University where he completed a Bachelor of Science in Kinesiology and fell in love with Athletic Therapy during his time with the Varsity Rugby Teams there. He then completed his Bachelor of AT, with distinction, from Concordia University. He graduated from the Ontario College of Health and Technology and acquired his certificate of registration to the College of Massage Therapist of Ontario (CMTO). He has worked with Baseball Canada, in the Greater Toronto Hockey League with the North York Rangers AAA Team, OHL/OHF Program of Excellence and the Team Ontario Volleyball High Performance Elite Mens Team as well as Team Ontario Box Lacrosse.He has since moved back to Montreal, and is now a registered LEVEL 3 Massage Therapist with the Association des Massothérapeutes du Québec (AMQ), the highest ranking massage therapist level. Steven works in private practice at Clinique MV in Westmount, Quebec, as well as one-on-one consultations. 

Steven has been afforded the opportunity to work with patients of all ages and skill levels in almost every sport, from the grandmother who just wants to improve her balance, to the elite, national level athlete who needs that extra drive. His goal is to look at the whole body and not just where you are feeling pain. Often times, the pain you are experiencing is a result of something up or down the chain in the body and if not addressed, will return later costing the patient hundreds of extra dollars. Due to Athletic Therapist's on-field work and the requirements to be able to asses and evaluate athletes in a very quick timeframe, ATs like Steven specialize in accurately assessing and deciding on what your injury is. It isn't a perfect science, but ATs are some of the best healthcare professionals at coming up with an accurate clinical impression which is vital for the patient. Steven has since added Massage Therapy to his skillset, and specializes in deep tissue, relaxation and fascial work. His ability to integrate all of his knowledge from Kinesiology, Athletic Therapy and Massage Therapy allows the client to receive preventative and rehabilitative treatments as needed. If that wasn't enough, during the quarantine, Steven was also able to become a certified TRX Suspension Trainer which just adds even more tools to his vast toolbox. 

After working with the 2018 U18 Baseball Canada team in Florida, Team Ontario Elite Volleyball and Lacrosse Teams, he has gained an even greater appreciation for elite level athletes and the rigours that the body goes through. As an elite baseball player, competitive hockey, tennis, volleyball and golfer in his youth, he relates to many of the patients he sees and his vast knowledge of sports allows for a more specific and impactful program to be designed and implemented. Utilizing the various specialties he has learned over his training affords the patient a thorough and all-encompassing rehab and treatment. One thing you can guarantee you will get from seeing Steven is 110% effort. He is a dedicated, honest and an enthusiastic hard worker who would love to see you in clinic anytime. 

`;

export const HOIT_ABOUT_FR = `
Steven Warsh est massothérapeute agréé auprès de l'AMQ et thérapeute du sport certifié (TSC) auprès de la CATA. Résidant à Montréal, au Québec, il privilégie une approche intégrative et holistique de la thérapie. Il a débuté sa formation à l'Université McGill, où il a obtenu un baccalauréat ès sciences en kinésiologie et s'est passionné pour la thérapie du sport lors de son passage au sein des équipes universitaires de rugby. Il a ensuite complété son baccalauréat en TSC, avec distinction, à l'Université Concordia. Diplômé du Collège des sciences de la santé et de la technologie de l'Ontario, il est membre de l'Ordre des massothérapeutes de l'Ontario (CMTO). Il a travaillé pour Baseball Canada, dans la Ligue de hockey du Grand Toronto (LHT) avec l'équipe AAA des Rangers de North York, au sein du Programme d'excellence de la Ligue de hockey de l'Ontario (OHL) et de la Fédération de hockey de l'Ontario (OHF), ainsi qu'avec l'équipe masculine d'élite de volleyball de l'Ontario et l'équipe de crosse en enclos de l'Ontario. De retour à Montréal, il est maintenant massothérapeute agréé de niveau 3 auprès de l'Association des massothérapeutes du Québec (AMQ), le plus haut niveau de certification. Steven exerce en cabinet privé à la Clinique MV de Westmount, au Québec, et offre également des consultations individuelles.

Il a eu l'opportunité de travailler avec des patients de tous âges et de tous niveaux, pratiquant presque tous les sports, de la grand-mère souhaitant simplement améliorer son équilibre à l'athlète de haut niveau national en quête d'un regain de motivation. Son objectif est d'adopter une approche holistique, considérant le corps dans son ensemble et non seulement la zone douloureuse. Souvent, la douleur ressentie résulte d'un problème systémique et, si elle n'est pas traitée, elle réapparaîtra, engendrant des coûts supplémentaires importants pour le patient. Du fait de leur travail sur le terrain et de la nécessité d'évaluer rapidement les athlètes, les thérapeutes du sport comme Steven sont spécialisés dans le diagnostic précis des blessures. Bien que ce ne soit pas une science exacte, les thérapeutes du sport figurent parmi les meilleurs professionnels de la santé pour établir un diagnostic clinique précis, essentiel pour le patient. Steven a depuis ajouté la massothérapie à ses compétences et se spécialise dans le massage des tissus profonds, la relaxation et le travail fascial. Sa capacité à intégrer toutes ses connaissances en kinésiologie, en thérapie sportive et en massothérapie permet au client de recevoir des traitements préventifs et de réadaptation adaptés à ses besoins. De plus, pendant le confinement, Steven a obtenu sa certification d'entraîneur en suspension TRX, enrichissant ainsi son expertise.

Après avoir travaillé avec l'équipe canadienne de baseball des moins de 18 ans en Floride en 2018, ainsi qu'avec les équipes d'élite de volleyball et de crosse de l'Ontario, il comprend encore mieux les athlètes de haut niveau et les exigences physiques qu'ils subissent. Ancien joueur de baseball d'élite et pratiquant de hockey, de tennis, de volleyball et de golf à un niveau compétitif, il comprend nombre de ses patients et sa vaste connaissance du sport lui permet de concevoir et de mettre en œuvre des programmes plus ciblés et efficaces. L'utilisation des différentes spécialités acquises au cours de sa formation offre au patient une réadaptation et un traitement complets et approfondis. Avec Steven, vous avez la garantie d'un engagement total. C'est un travailleur acharné, dévoué, honnête et enthousiaste, qui serait ravi de vous recevoir à la clinique à tout moment.`;
